### ISSUE TITLE
Converted table with svg item gets merged into a single column

### ISSUE THREAD

**Issue by ksanthosh82** [d3-node/d3node-output#10]
When I convert the generated html having a table element with a column having another svg element, all svg items gets into a single column. Generated HTML through d3node looks fine. Pasted code below and attached generated image and HTML
**Generated SVG:**
![pieyearlyrajeshkumar pccslogistic com](https://user-images.githubusercontent.com/8243661/38470600-eb0d4cb8-3b82-11e8-87e2-6244963c55db.png)
**HTML generated:**
`<html><head></head><body><div id="container">
            <h2>Shipment Performance</h2>
            <div id="chart"><svg xmlns="http://www.w3.org/2000/svg" width="375" height="300"><defs><style type="text/css"><![CDATA[ 
            .arc text {font:10px sans-serif; text-anchor: middle;}
            .arc path {stroke: #fff;}
            .legend tr{border-bottom:1px solid grey;}
            .legend tr:first-child{    border-top:1px solid grey; }
            .legend{
                font-size: 10px;
                margin-bottom:150px;
                display:inline-block;
                border-collapse: collapse;
                border-spacing: 0px;
            }
            .legend td{
                padding:2px 2px;
                vertical-align:bottom;
            }
            .legendFreq, .legendPerc{
                align:right;
                width:50px;
            }
         ]]></style></defs><g transform="translate(150, 150)"><g class="arc"><path d="M8.572527594031473e-15,-140A140,140,0,1,1,-33.19532223326901,-136.00761222016007L0,0Z" style="fill: #00cc00;"></path><text transform="translate(13.134998523038563,109.21296541070467)" dy=".35em">Achieved</text></g><g class="arc"><path d="M-33.19532223326901,-136.00761222016007A140,140,0,0,1,9.862739597592311e-14,-140L0,0Z" style="fill: #ff4d4d;"></path><text transform="translate(-13.134998523038528,-109.21296541070467)" dy=".35em">Failed</text></g><g transform="translate(50, 50)"><table class="legend"><tbody><tr><td><svg width="16" height="16"><rect width="16" height="16" fill="#00cc00"></rect></svg></td><td>Achieved</td><td class="legendFreq">96.19%</td></tr><tr><td><svg width="16" height="16"><rect width="16" height="16" fill="#ff4d4d"></rect></svg></td><td>Failed</td><td class="legendFreq">3.81%</td></tr></tbody></table></g></g></svg></div>
            </div>
        </body></html>`

**Sample piece of code:**
`        const svg = d3n.createSVG(_width, _height)
            .append('g')
            .attr('transform', `translate(${_radius}, ${_radius})`);            
        // create table for legend.
        var legend = svg.append('g')
            .attr('transform', `translate(50, 50)`)
            .append("table")
            .attr("class", "legend");
        // create one row per segment.
        var tr = legend.append("tbody").selectAll("tr").data(data).enter()
            .append("tr");
        // create the first column for each segment.        
        tr.append("td").text(function(d){ 
            return d.key;
        });
        // create the second column for each segment.
        tr.append("td").attr("class",'legendFreq')
            .text(function(d){ 
                return d.value+"%";
                //return d3.format("%")(d.value/100);
            });
        // create the third column for each segment.
        tr.append("td")
            .append("svg")
                .attr("width", '14').attr("height", '14')
            .append("rect")
                .attr("width", '14').attr("height", '14')
                .attr("fill",function(d){ 
                    return segColor(d.key); 
                });

        function getLegend(d,aD){ // Utility function to compute percentage.
            return d3.format("%")(d.value);
        }`

**Comment by bradoyler** [comment]
That's that a valid svg document. Look up how to ["append HTML table into SVG with foreignObject"](https://stackoverflow.com/questions/38257721/append-a-table-onto-a-svg-by-id-using-d3). 

However, I would suggest creating html elements (table, div, etc) within HTML.
